version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/action-cache
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test:cover
